apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  name: spring-hello 
  labels:
    name: spring-hello
spec:
  triggers:
    - type: ConfigChange
  source:
    contextDir: "Day5/ImageStreamAndBuildConfig"
    type: Git
    git:
      uri: 'https://github.com/tektutor/openshift-aug-2022.git'
  strategy:
    type: Docker
  output:
    to:
      kind: ImageStreamTag
      name: 'tektutor-spring-hello:latest'
