apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pvc-jegan
spec:
  selector:
    matchLabels:
      name: jegan
  accessModes:
    - ReadWriteMany
  volumeMode: Filesystem
  resources:
    requests:
      storage: 100Mi
