apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: mysql
  name: mysql
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
      - env:
        - name: MYSQL_ROOT_PASSWORD
          value: root
        image: bitnami/mysql:latest
        imagePullPolicy: Always
        name: mysql
        volumeMounts:
        - name: mysql-storage
          mountPath: /bitnami/mysql/data  
      volumes:
      - name: mysql-storage 
        persistentVolumeClaim:
          claimName: mysql-pvc-jegan
