apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pvc-jegan
  labels:
    type: mysql 
    name: jegan
spec:
  selector:
    matchLabels:
      type: mysql
      name: jegan
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 100Mi
