apiVersion: batch/v1 
kind: CronJob
metadata:
  name: hello
spec:
  schedule: "* * * * *"
  jobTemplate:
    spec:
      suspend: true
      template:
        spec:
          containers:
          - name: hello
            image: busybox:1.28
            command:
            - bin/sh
            - -c
            - echo "Hello from OpenShift cluster ..."
          restartPolicy: OnFailure
